redis:
  cluster:
    nodes:
      - redis-node-1:6379
      - redis-node-2:6379
      - redis-node-3:6379
    password:
    connectionTimeout: 3000
    soTimeout: 3000
    maxAttempts: 5
    maxTotal: 100
    maxIdle: 20
    minIdle: 5