spring:
  application:
    name: patient-service
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/medibook}

server:
  port: 8082
